---
- hosts: "{{ bk }}"
  gather_facts: false
  remote_user: root
  vars:
    zoo_port: 2181
    bk_journal_dir:  /opt/pulsar/data/bookkeeper/journal
    bk_ledger_dir: /opt/pulsar/data/bookkeeper/ledger
  tasks:
    - name: "copy pulsar compressed file"
      copy:
        src: /opt/pulsar/apache-pulsar-2.4.0-bin.tar.gz
        dest: /opt/pulsar/
        mode: 0644
    
    - name: "decompress file"
      unarchive: src=/opt/pulsar/apache-pulsar-2.4.0-bin.tar.gz dest=/opt/pulsar/ copy=no
   
    - name: "rename"
      shell: mv /opt/pulsar/apache-pulsar-2.4.0 /opt/pulsar/bookkeeper-2.4.0

    - name: " create bookkeeper journal dir "
      file:
        path: "{{ bk_journal_dir }}"
        state: directory
        mode: 0755

    - name: " create bookkeeper ledger dir "
      file:
        path: "{{ bk_ledger_dir }}"
        state: directory
        mode: 0755

    - name: "config bookkeeper "
      template:
        src: /root/tools/playbooks/pulsar_install/bookkeeper/templates/bookkeeper.conf.j2
        dest: /opt/pulsar/bookkeeper-2.4.0/conf/bookkeeper.conf
        mode: 0755
