---
- hosts: "{{ broker }}"
  gather_facts: false
  remote_user: root
  tasks:
    - name: "copy pulsar compressed file"
      copy:
        src: /opt/pulsar/apache-pulsar-2.4.0-bin.tar.gz
        dest: /opt/pulsar/
        mode: 0644

    - name: "decompress file"
      unarchive: src=/opt/pulsar/apache-pulsar-2.4.0-bin.tar.gz dest=/opt/pulsar/ copy=no

    - name: "rename"
      shell: mv /opt/pulsar/apache-pulsar-2.4.0 /opt/pulsar/broker-2.4.0
